(defun getLine ()
  (interactive)
  (setq columnNumber (point))
  (insert "</>")
  (goto-char (+ columnNumber 1))
  (message  (buffer-substring-no-properties (line-beginning-position) (line-end-position)))
  )

(defun getLine2 ()
  (interactive)
  (insert ">")
(setq columnNumber (- (current-column) 1))
(setq cursorPos (point))
(setq lineStr  (buffer-substring-no-properties (line-beginning-position) (line-end-position)))
(setq diff 9999)
(setq pos 0)
(setq lis '())
(dotimes (index (- (length lineStr) 1))
  (if(= 60 (aref lineStr index))
      
       (if(< (- columnNumber index) diff)
	   (setq pos index))
       )
)
(setq node (split-string (substring lineStr (+ pos 1) columnNumber)))

(insert "<")
(setq currenPos (point))
(goto-char (+ currenPos 1))
(insert (car node))
(goto-char cursorPos)
)
